name: Compile LaTeX CV

on:
  push:
    tags:
      - '*'  # Runs on all tags
  pull_request:  
    branches:
      - '**'  # Runs on all PRs
  workflow_dispatch:  # Allows manual triggering if needed

permissions:
  contents: write  # Required for uploading release assets

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile CV using latexmk
        run: latexmk -pdf -interaction=nonstopmode -shell-escape cv.tex

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Brendan_Devenney_CV.pdf
          generate_release_notes: true
          make_latest: true
